In [2]:
import pandas as pd

In [3]:
#series data structure 1-Dimensional
x=[3,4,5,6,7,8]
var=pd.Series(x)
print(var)

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64

In [4]:
print(type(var))

<class 'pandas.core.series.Series'>

In [5]:
#using custom index and desired datatype
# and defining name
x=[1,2,3,4]

var= pd.Series(x,index=['a','b','c','d'],dtype='float',name="python")
print(var)

a    1.0
b    2.0
c    3.0
d    4.0
Name: python, dtype: float64

In [6]:
dic={"name":['a','b','c','d'],'pop':[12,13,14,15],'rank':[1,4,3,2]}
var_1=pd.Series(dic)
print(var_1)

name        [a, b, c, d]
pop     [12, 13, 14, 15]
rank        [1, 4, 3, 2]
dtype: object

In [7]:
var_2= pd.Series(12)
print(var_2)
print()
var_2=pd.Series(12,index=[1,2,3,4,5,6])
print(var_2)

0    12
dtype: int64

1    12
2    12
3    12
4    12
5    12
6    12
dtype: int64

In [8]:
# there is is mismatch of rows in numpy we will get broadcasting error
s1=pd.Series([1,2,3,4])
s2=pd.Series([1,2,3,4,5,6,7])
print(s1,s2)

0    1
1    2
2    3
3    4
dtype: int64 0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [9]:
print(s1+s2) # for extra rows we will get Nan

0    2.0
1    4.0
2    6.0
3    8.0
4    NaN
5    NaN
6    NaN
dtype: float64

# DataFrame
## 2d data

In [10]:
#from list 

l=[1,2,3,4,5,6]
df=pd.DataFrame(l)
print(df)
print(type(df))

   0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>

In [11]:
# using dictionary
d={'a':[1,1,1,1],'b':[2,2,2,2],'c':[3,3,3,3]}

In [12]:
df=pd.DataFrame(d,columns=["a","b"],index=['a','s','c','d']) # displays only a,b column

In [13]:
print(df)

   a  b
a  1  2
s  1  2
c  1  2
d  1  2

In [14]:
print(df['b']['c']) # df[column][row]

2

In [15]:
list_1=[[1,2,3,4],[2,3,4,5]]
df_2=pd.DataFrame(list_1)
print(df_2)

   0  1  2  3
0  1  2  3  4
1  2  3  4  5

In [16]:
dic={'s':pd.Series([1,2,3,4]),'r':pd.Series([2,3,4,5])}
df_2=pd.DataFrame(dic)
print(df_2)

   s  r
0  1  2
1  2  3
2  3  4
3  4  5

# Arthematic Operations in pandas

In [17]:
# we will perform arthematic operations on the column data 
dic={'a':[1,2,3,4],'b':[3,4,5,6]}
df_3=pd.DataFrame(dic)

In [18]:
print(df_3)

   a  b
0  1  3
1  2  4
2  3  5
3  4  6

In [19]:
# df_3['c']=df_3['a']+df['b']
# print(df_3)

df_3['c']=(df_3['a']+df_3['b'])
print(df_3)
print()
df_3['c']=(df_3['a']-df_3['b'])
print(df_3)
print()
df_3['c']=(df_3['a']*df_3['b'])
print(df_3)
print()
df_3['c']=(df_3['a']/df_3['b'])
print(df_3)
print()
df_3['c']=(df_3['a']//df_3['b'])
print(df_3)
print()

   a  b   c
0  1  3   4
1  2  4   6
2  3  5   8
3  4  6  10

   a  b  c
0  1  3 -2
1  2  4 -2
2  3  5 -2
3  4  6 -2

   a  b   c
0  1  3   3
1  2  4   8
2  3  5  15
3  4  6  24

   a  b         c
0  1  3  0.333333
1  2  4  0.500000
2  3  5  0.600000
3  4  6  0.666667

   a  b  c
0  1  3  0
1  2  4  0
2  3  5  0
3  4  6  0

In [20]:
df_3['c']=((df_3['a']<3) & (df_3['b']<5))
print(df_3)
print()

   a  b      c
0  1  3   True
1  2  4   True
2  3  5  False
3  4  6  False

# Delete and Insert Data

In [21]:
dic={'A':[1,2,3,4,5],'B':[6,7,8,9,10]}

var=pd.DataFrame(dic)

var.insert(2,'C',[1,2,3,4,5])
print(var)

   A   B  C
0  1   6  1
1  2   7  2
2  3   8  3
3  4   9  4
4  5  10  5

In [22]:
# var.insert(index,"column name",[data])

In [23]:
var.insert(2,'c',[10,11,12,13,14])
print(var)

   A   B   c  C
0  1   6  10  1
1  2   7  11  2
2  3   8  12  3
3  4   9  13  4
4  5  10  14  5

In [24]:
# copying data from existing table

var['d']=var['A'][:3]
print(var)

   A   B   c  C    d
0  1   6  10  1  1.0
1  2   7  11  2  2.0
2  3   8  12  3  3.0
3  4   9  13  4  NaN
4  5  10  14  5  NaN

In [25]:
# deleting data
var['d']=var['A'][:3]

var.pop('d')
print(var)

   A   B   c  C
0  1   6  10  1
1  2   7  11  2
2  3   8  12  3
3  4   9  13  4
4  5  10  14  5

# Reading from csv file 
# write in csv file

In [26]:
# csv : data in plain text format and are separated by commas ( comma separated values )
# xls: excel sheet files ( binary format which holds information about all worksheets in a file 
# including content and formatting

## write CSV

In [27]:
df=pd.DataFrame({'A':[1,2,3,4,5],'B':[199,299,399,499,599]})
df.insert(2,"C",[100,200,300,400,500])
print(df)

   A    B    C
0  1  199  100
1  2  299  200
2  3  399  300
3  4  499  400
4  5  599  500

In [28]:
df.to_csv('newSample.csv')
df.to_csv('newSample_without_index.csv',index=False) #creating file with default index
df.to_csv('newSample_with_custom_columnName.csv',index=False,header=[1,2,3]) # with different column names

# Read CSV

In [29]:
csv_1=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\newSample_with_custom_columnName.csv")
print(csv_1)

   1    2    3
0  1  199  100
1  2  299  200
2  3  399  300
3  4  499  400
4  5  599  500

In [30]:
csv_2=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\DataSets\Teen_Mental_Health_Dataset.csv")

In [31]:
print(csv_2)

      age  gender  daily_social_media_hours platform_usage  sleep_hours  \
0      14    male                       7.9      Instagram          7.4
1      19  female                       1.9         TikTok          8.0
2      17  female                       1.3      Instagram          7.6
3      15    male                       7.4         TikTok          6.9
4      15  female                       4.7           Both          4.9
...   ...     ...                       ...            ...          ...
1195   18  female                       6.8      Instagram          6.6
1196   16    male                       2.3           Both          8.0
1197   14  female                       1.7           Both          8.7
1198   15    male                       3.9           Both          8.5
1199   16  female                       4.7         TikTok          6.5

      screen_time_before_sleep  academic_performance  physical_activity  \
0                          2.9                  3.01                1.5
1                          2.9                  3.22                0.8
2                          0.5                  3.92                0.0
3                          1.6                  3.48                0.8
4                          3.0                  2.37                1.4
...                        ...                   ...                ...
1195                       2.0                  2.76                1.0
1196                       1.9                  2.12                0.4
1197                       0.7                  3.98                0.8
1198                       2.1                  3.19                0.6
1199                       1.0                  2.91                0.9

     social_interaction_level  stress_level  anxiety_level  addiction_level  \
0                         low             2              2                1
1                        high             8              1               10
2                        high             2              4                2
3                      medium             1              7                9
4                      medium             3              5                2
...                       ...           ...            ...              ...
1195                      low             3              4                4
1196                     high             7              4                4
1197                     high             1              1                1
1198                     high             7              9                9
1199                   medium             5              7                3

      depression_label
0                    0
1                    0
2                    0
3                    0
4                    0
...                ...
1195                 0
1196                 0
1197                 0
1198                 0
1199                 0

[1200 rows x 13 columns]

In [32]:

csv_2=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\DataSets\Teen_Mental_Health_Dataset.csv",nrows=9,skiprows=[1],usecols=[0,1,2,3,4])
print(csv_2) # nrows=1 reading 1 row
             #usecols=['column names/ index']
             #skiprows=[rows index to skip]

   age  gender  daily_social_media_hours platform_usage  sleep_hours
0   19  female                       1.9         TikTok          8.0
1   17  female                       1.3      Instagram          7.6
2   15    male                       7.4         TikTok          6.9
3   15  female                       4.7           Both          4.9
4   19  female                       7.4           Both          4.4
5   18  female                       2.5      Instagram          6.4
6   16    male                       4.0           Both          4.2
7   19  female                       3.3         TikTok          5.0
8   15    male                       1.9         TikTok          4.9

In [33]:

csv_2=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\DataSets\Teen_Mental_Health_Dataset.csv",nrows=9,skiprows=[1],usecols=[0,1,2,3,4],index_col='age')
print(csv_2) 
# index_col=age

     gender  daily_social_media_hours platform_usage  sleep_hours
age
19   female                       1.9         TikTok          8.0
17   female                       1.3      Instagram          7.6
15     male                       7.4         TikTok          6.9
15   female                       4.7           Both          4.9
19   female                       7.4           Both          4.4
18   female                       2.5      Instagram          6.4
16     male                       4.0           Both          4.2
19   female                       3.3         TikTok          5.0
15     male                       1.9         TikTok          4.9

In [34]:

csv_2=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\DataSets\Teen_Mental_Health_Dataset.csv",nrows=9,skiprows=[1],usecols=[0,1,2,3,4])
print(csv_2)

   age  gender  daily_social_media_hours platform_usage  sleep_hours
0   19  female                       1.9         TikTok          8.0
1   17  female                       1.3      Instagram          7.6
2   15    male                       7.4         TikTok          6.9
3   15  female                       4.7           Both          4.9
4   19  female                       7.4           Both          4.4
5   18  female                       2.5      Instagram          6.4
6   16    male                       4.0           Both          4.2
7   19  female                       3.3         TikTok          5.0
8   15    male                       1.9         TikTok          4.9

In [35]:
#custom header


csv_2=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\DataSets\Teen_Mental_Health_Dataset.csv",nrows=9,skiprows=[1],header=[1])
print(csv_2) #header=[1] using row 1 values as header

   19  female  1.9     TikTok  8.0  2.9  3.22  0.8    high  8   1  10  0
0  17  female  1.3  Instagram  7.6  0.5  3.92  0.0    high  2   4   2  0
1  15    male  7.4     TikTok  6.9  1.6  3.48  0.8  medium  1   7   9  0
2  15  female  4.7       Both  4.9  3.0  2.37  1.4  medium  3   5   2  0
3  19  female  7.4       Both  4.4  2.4  2.63  0.6    high  3   5   7  0
4  18  female  2.5  Instagram  6.4  2.4  2.63  0.7     low  2   2   5  0
5  16    male  4.0       Both  4.2  0.5  2.40  1.3     low  6  10   5  0
6  19  female  3.3     TikTok  5.0  2.1  2.04  0.9    high  1  10   9  0
7  15    male  1.9     TikTok  4.9  1.5  3.77  1.1    high  1   1   4  0
8  16    male  7.2       Both  5.8  2.9  3.16  1.2  medium  5   8   9  0

In [36]:
# Name parameter 


csv_2=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\DataSets\Teen_Mental_Health_Dataset.csv",nrows=2,usecols=[0,1,2,3,4],skiprows=[1],names=['1','2','3','4','5'])
print(csv_2) #header=[1] using row 1 values as header

     1       2                         3               4            5
0  age  gender  daily_social_media_hours  platform_usage  sleep_hours
1   19  female                       1.9          TikTok          8.0

In [37]:
# Removing header
# Name parameter 


csv_2=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\DataSets\Teen_Mental_Health_Dataset.csv",nrows=4,usecols=[0,1,2,3,4],skiprows=[1],header=None,dtype={"sleep_hours":"int"}).add_prefix('col')
print(csv_2) #header=[1] using row 1 values as header 
#changing datatype of the columns

  col0    col1                      col2            col3         col4
0  age  gender  daily_social_media_hours  platform_usage  sleep_hours
1   19  female                       1.9          TikTok          8.0
2   17  female                       1.3       Instagram          7.6
3   15    male                       7.4          TikTok          6.9

# Pandas Functions

In [38]:
csv_1=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\newSample_without_index.csv")

In [39]:
csv_1.index # we get the index of the csv file

RangeIndex(start=0, stop=5, step=1)

In [40]:
csv_1.columns # we get column names

Index(['A', 'B', 'C'], dtype='object')

In [41]:
csv_1.describe()

              A           B           C
count  5.000000    5.000000    5.000000
mean   3.000000  399.000000  300.000000
std    1.581139  158.113883  158.113883
min    1.000000  199.000000  100.000000
25%    2.000000  299.000000  200.000000
50%    3.000000  399.000000  300.000000
75%    4.000000  499.000000  400.000000
max    5.000000  599.000000  500.000000

In [42]:
csv_1.head() # first 5

   A    B    C
0  1  199  100
1  2  299  200
2  3  399  300
3  4  499  400
4  5  599  500

In [43]:
csv_1.tail() # last 5

   A    B    C
0  1  199  100
1  2  299  200
2  3  399  300
3  4  499  400
4  5  599  500

In [44]:
 csv_1[0:2] # 2 rows data

   A    B    C
0  1  199  100
1  2  299  200

In [45]:
type(csv_1)

pandas.core.frame.DataFrame

In [46]:
csv_1.index.array #indexes in array

<NumpyExtensionArray>
[0, 1, 2, 3, 4]
Length: 5, dtype: int64

In [47]:
# convert to numpy array

csv_1.to_numpy()

array([[  1, 199, 100],
       [  2, 299, 200],
       [  3, 399, 300],
       [  4, 499, 400],
       [  5, 599, 500]], dtype=int64)

In [48]:
import numpy as np
v=np.asarray(csv_1)
print(v)

[[  1 199 100]
 [  2 299 200]
 [  3 399 300]
 [  4 499 400]
 [  5 599 500]]

In [49]:
csv_1.sort_index(axis=0,ascending=False) # descending order

   A    B    C
4  5  599  500
3  4  499  400
2  3  399  300
1  2  299  200
0  1  199  100

In [50]:
csv_1['A'][1]=88
print(csv_1)

    A    B    C
0   1  199  100
1  88  299  200
2   3  399  300
3   4  499  400
4   5  599  500

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11576\1227647664.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv_1['A'][1]=88

In [51]:
csv_1.loc[0,'A']=999
print(csv_1)

     A    B    C
0  999  199  100
1   88  299  200
2    3  399  300
3    4  499  400
4    5  599  500

In [52]:
print(csv_1.loc[0,'A']) # row, column

999

In [53]:
csv_1.iloc[0,2] # row,cloumn

100

In [54]:
csv_1=csv_1.drop('A',axis=1)
print(csv_1)

     B    C
0  199  100
1  299  200
2  399  300
3  499  400
4  599  500

# handling missing values
## dropNa fillNa

In [55]:
csv_1=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\DataSets\reduced.csv")

In [56]:
csv_1

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,NaN,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.40,NaN,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,NaN,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [57]:
csv_1.dropna()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [58]:
csv_1.dropna(axis=0) # 1 for column 0 for row

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [59]:
csv_1.dropna(how='all') # all  if all row values are nan then entire row is removed any if one nan value

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,NaN,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.40,NaN,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,NaN,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [60]:
csv_1.dropna(subset=['gender']) # if nan is present in column then its removed

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,NaN,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.40,NaN,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,NaN,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [61]:
csv_1.dropna(inplace=True) # all null values have been removed and new data set is created 
csv_1

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [62]:
csv_1.dropna(thresh=1) # based on the count we enter if we enter 1 then
                       # if one value is present in the row then the entire row is dropped

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

# fillna

In [63]:
csv_1=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\DataSets\reduced.csv")
csv_1.fillna('python')

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,python,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,python,python,python,python,python,python,python,python,python,python,python,python,python
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.4,python,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,python,TikTok,4.9,1.5,3.77,1.1,python,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [64]:
csv_1.fillna({"age":12,"gender":"female","daily_social_media_hours":1})

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,NaN,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,12.0,female,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.40,NaN,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,1.0,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [65]:
# will with backward values / previous values


csv_1.fillna(method="ffill")  # forward filling

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11576\44543547.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_1.fillna(method="ffill")  # forward filling

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,6.9,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,15.0,female,4.7,Both,6.9,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.40,0.7,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,3.3,TikTok,4.9,1.5,3.77,1.1,high,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [66]:
csv_1.fillna(method="bfill") #backward filling

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11576\841736765.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_1.fillna(method="bfill") #backward filling

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,6.4,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.40,0.9,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,7.2,TikTok,4.9,1.5,3.77,1.1,medium,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [67]:
csv_1.fillna(method="bfill",axis=1) #backward filling

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11576\1717796443.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_1.fillna(method="bfill",axis=1) #backward filling
C:\Users\Administrator\AppData\Local\Temp\ipykernel_11576\1717796443.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  csv_1.fillna(method="bfill",axis=1) #backward filling

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,3.0,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.4,low,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,TikTok,TikTok,4.9,1.5,3.77,1.1,1.0,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [68]:
csv_1=pd.read_csv(r"C:\Users\Administrator\Desktop\DATA_SCIENCE\Pandas\DataSets\reduced.csv")
csv_1.fillna('AAAAAAAAAAAAAAAAAAAA',limit=1,axis=1) # only 1 nan is replaced

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,AAAAAAAAAAAAAAAAAAAA,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,AAAAAAAAAAAAAAAAAAAA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.4,AAAAAAAAAAAAAAAAAAAA,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,AAAAAAAAAAAAAAAAAAAA,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

# Handling missing Data ( replace and interpolate )

# Replace

In [69]:
csv_1.replace(to_replace="male",value="M")

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,M,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,M,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,NaN,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,M,4.0,Both,4.2,0.5,2.40,NaN,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,M,NaN,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,M,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,M,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [70]:
csv_1.replace(["male"],"m")

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,m,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,m,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,NaN,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,m,4.0,Both,4.2,0.5,2.40,NaN,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,m,NaN,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,m,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,m,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [71]:
#using regex to replace 

csv_1.replace("[A-Za-z]","python",regex=True)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,pythonpythonpythonpython,7.9,pythonpythonpythonpythonpythonpythonpythonpyth...,7.4,2.9,3.01,1.5,pythonpythonpython,2.0,2.0,1.0,0.0
1,19.0,pythonpythonpythonpythonpythonpython,1.9,pythonpythonpythonpythonpythonpython,8.0,2.9,3.22,0.8,pythonpythonpythonpython,8.0,1.0,10.0,0.0
2,17.0,pythonpythonpythonpythonpythonpython,1.3,pythonpythonpythonpythonpythonpythonpythonpyth...,7.6,0.5,3.92,0.0,pythonpythonpythonpython,2.0,4.0,2.0,0.0
3,15.0,pythonpythonpythonpython,7.4,pythonpythonpythonpythonpythonpython,6.9,1.6,3.48,0.8,pythonpythonpythonpythonpythonpython,1.0,7.0,9.0,0.0
4,15.0,pythonpythonpythonpythonpythonpython,4.7,pythonpythonpythonpython,NaN,3.0,2.37,1.4,pythonpythonpythonpythonpythonpython,3.0,5.0,2.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,pythonpythonpythonpythonpythonpython,2.5,pythonpythonpythonpythonpythonpythonpythonpyth...,6.4,2.4,2.63,0.7,pythonpythonpython,2.0,2.0,5.0,0.0
7,16.0,pythonpythonpythonpython,4.0,pythonpythonpythonpython,4.2,0.5,2.40,NaN,pythonpythonpython,6.0,10.0,5.0,0.0
8,19.0,pythonpythonpythonpythonpythonpython,3.3,pythonpythonpythonpythonpythonpython,5.0,2.1,2.04,0.9,pythonpythonpythonpython,1.0,10.0,9.0,0.0
9,15.0,pythonpythonpythonpython,NaN,pythonpythonpythonpythonpythonpython,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,pythonpythonpythonpython,7.2,pythonpythonpythonpython,5.8,2.9,3.16,1.2,pythonpythonpythonpythonpythonpython,5.0,8.0,9.0,0.0
11,13.0,pythonpythonpythonpython,4.9,pythonpythonpythonpythonpythonpythonpythonpyth...,4.7,2.5,3.92,1.2,pythonpythonpython,1.0,10.0,8.0,0.0

In [72]:
csv_1.replace({"gender":["male"]},"m")

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,m,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,m,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,NaN,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,m,4.0,Both,4.2,0.5,2.40,NaN,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,m,NaN,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,m,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,m,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [73]:
csv_1.replace({"gender":{"male":"m","female":"f"}})

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,m,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,f,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,f,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,m,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,f,4.7,Both,NaN,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,f,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,m,4.0,Both,4.2,0.5,2.40,NaN,low,6.0,10.0,5.0,0.0
8,19.0,f,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,m,NaN,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,m,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,m,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [74]:
# backward / forward repalce

csv_1.replace(1,method="ffill")

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11576\2587230535.py:3: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv_1.replace(1,method="ffill")

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,2.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,2.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,NaN,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.40,NaN,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,6.0,10.0,9.0,0.0
9,15.0,male,NaN,TikTok,4.9,1.5,3.77,1.1,NaN,6.0,10.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,5.0,10.0,8.0,0.0

In [75]:
csv_1.replace(16.0,method="ffill",limit=2)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11576\2579017983.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv_1.replace(16.0,method="ffill",limit=2)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,NaN,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,18.0,male,4.0,Both,4.2,0.5,2.40,NaN,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,NaN,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,15.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [76]:
# a=csv_1.replace(13.0,method="ffill",limit=1,inplace=True)
# a

# intepolate
## automatically filling values

In [77]:
csv_1.interpolate()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11576\3094693765.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_1.interpolate()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.90,Instagram,7.400000,2.9,3.01,1.50,low,2.0,2.0,1.0,0.0
1,19.0,female,1.90,TikTok,8.000000,2.9,3.22,0.80,high,8.0,1.0,10.0,0.0
2,17.0,female,1.30,Instagram,7.600000,0.5,3.92,0.00,high,2.0,4.0,2.0,0.0
3,15.0,male,7.40,TikTok,6.900000,1.6,3.48,0.80,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.70,Both,6.733333,3.0,2.37,1.40,medium,3.0,5.0,2.0,0.0
5,16.5,NaN,3.60,NaN,6.566667,2.7,2.50,1.05,NaN,2.5,3.5,3.5,0.0
6,18.0,female,2.50,Instagram,6.400000,2.4,2.63,0.70,low,2.0,2.0,5.0,0.0
7,16.0,male,4.00,Both,4.200000,0.5,2.40,0.80,low,6.0,10.0,5.0,0.0
8,19.0,female,3.30,TikTok,5.000000,2.1,2.04,0.90,high,1.0,10.0,9.0,0.0
9,15.0,male,5.25,TikTok,4.900000,1.5,3.77,1.10,NaN,1.0,1.0,4.0,0.0
10,16.0,male,7.20,Both,5.800000,2.9,3.16,1.20,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.90,Instagram,4.700000,2.5,3.92,1.20,low,1.0,10.0,8.0,0.0

In [78]:
csv_1.interpolate(method="nearest",axis=0) # axis=0 column by column 1 row by row

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11576\1075942253.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_1.interpolate(method="nearest",axis=0) # axis=0 column by column 1 row by row

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,6.9,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,15.0,NaN,4.7,NaN,6.4,3.0,2.37,1.4,NaN,3.0,5.0,2.0,0.0
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.40,0.7,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,3.3,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

In [79]:
csv_1.interpolate(method="nearest",axis=0,limit_direction="forward",limit=2)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11576\270469234.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_1.interpolate(method="nearest",axis=0,limit_direction="forward",limit=2)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14.0,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2.0,2.0,1.0,0.0
1,19.0,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8.0,1.0,10.0,0.0
2,17.0,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2.0,4.0,2.0,0.0
3,15.0,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1.0,7.0,9.0,0.0
4,15.0,female,4.7,Both,6.9,3.0,2.37,1.4,medium,3.0,5.0,2.0,0.0
5,15.0,NaN,4.7,NaN,6.4,3.0,2.37,1.4,NaN,3.0,5.0,2.0,0.0
6,18.0,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2.0,2.0,5.0,0.0
7,16.0,male,4.0,Both,4.2,0.5,2.40,0.7,low,6.0,10.0,5.0,0.0
8,19.0,female,3.3,TikTok,5.0,2.1,2.04,0.9,high,1.0,10.0,9.0,0.0
9,15.0,male,3.3,TikTok,4.9,1.5,3.77,1.1,NaN,1.0,1.0,4.0,0.0
10,16.0,male,7.2,Both,5.8,2.9,3.16,1.2,medium,5.0,8.0,9.0,0.0
11,13.0,male,4.9,Instagram,4.7,2.5,3.92,1.2,low,1.0,10.0,8.0,0.0

# merge and concat

In [108]:
var1=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,33,8]})
var2=pd.DataFrame({'A':[1,2,3,5],'B':[5,6,7,8]})
# print(pd.merge(A,B))
# merging common port 

print(pd.merge(var1,var2,on='A'))
print()
print()
# pd.merge(var1,var2,how="right")
print()
pd.merge(var1,var2,how="outer",indicator=True)
print()

pd.merge(var1,var2,left_index=True,right_index=True,suffixes=("name","id")) # displays all data

   A  B_x  B_y
0  1    5    5
1  2    6    6
2  3   33    7

   Aname  Bname  Aid  Bid
0      1      5    1    5
1      2      6    2    6
2      3     33    3    7
3      4      8    5    8

# concat

In [112]:
#to join 2 series

sr1=pd.Series([1,2,3,4])
sr2=pd.Series([5,6,7,8])

sr1
print()
sr2

0    5
1    6
2    7
3    8
dtype: int64

In [114]:
pd.concat([sr1,sr2])

0    1
1    2
2    3
3    4
0    5
1    6
2    7
3    8
dtype: int64

In [117]:
d1=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
d2=pd.DataFrame({'A':[1,2,3,5],'C':[5,6,7,8]})


pd.concat([d1,d2])

   A    B    C
0  1  5.0  NaN
1  2  6.0  NaN
2  3  7.0  NaN
3  4  8.0  NaN
0  1  NaN  5.0
1  2  NaN  6.0
2  3  NaN  7.0
3  5  NaN  8.0

In [119]:
pd.concat([d1,d2],axis=1) # column merger

   A  B  A  C
0  1  5  1  5
1  2  6  2  6
2  3  7  3  7
3  4  8  5  8

In [120]:
d1=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
d2=pd.DataFrame({'A':[1,2],'C':[9,18]})

In [124]:
pd.concat([d1,d2],axis=1,join="inner")

   A  B  A   C
0  1  5  1   9
1  2  6  2  18

In [135]:
d1=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
d2=pd.DataFrame({'A':[1,2,3,4],'C':[9,18,10,11]})

pd.concat([d1,d2],keys=["d1","d2"])

      A    B     C
d1 0  1  5.0   NaN
   1  2  6.0   NaN
   2  3  7.0   NaN
   3  4  8.0   NaN
d2 0  1  NaN   9.0
   1  2  NaN  18.0
   2  3  NaN  10.0
   3  4  NaN  11.0

# join and Append

In [147]:
d1=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]},index=['a','b','c','d'])
d2=pd.DataFrame({'C':[1,32,5,4],'D':[9,18,10,11]},index=['a','b','c','d'])

In [157]:

d1.join(d2,how="outer")

   A  B   C   D
a  1  5   1   9
b  2  6  32  18
c  3  7   5  10
d  4  8   4  11

# Append

In [169]:
d1=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
d2=pd.DataFrame({'B':[1,2],'C':[5,6]})
pd.concat([d1,d2])

     A  B    C
0  1.0  5  NaN
1  2.0  6  NaN
2  3.0  7  NaN
3  4.0  8  NaN
0  NaN  1  5.0
1  NaN  2  6.0

In [170]:
# pivot and melt